name = "CollatzConjecture"
version = "0.1.0"
keywords = ["math", "number theory", "collatz"]
defaultTargets = ["CollatzConjecture"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.27.0"

[[require]]
name = "formal_conjectures"
git = "https://github.com/flound1129/formal-conjectures.git"
rev = "main"

[[lean_lib]]
name = "CollatzConjecture"
